# Generated by Django 4.1.1 on 2022-09-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profileimg",
            field=models.ImageField(
                default="blank-profile-picture.png", upload_to="profile_images"
            ),
        ),
    ]
